### PR TITLE
Move auto_contiguous before lowering

### PR DESCRIPTION
**Pull request by pfultz2**
This should fix the perf isssues.

### CODE REVIEW

**Comment by causten** [comment]
Perf report looks pretty bad.  Is there something else needed?

**Comment by pfultz2** [comment]
Perf regression should be fixed by #3494.

**Comment by TedThemistokleous** [comment]
> Perf regression should be fixed by #3494.

Do we close this out then or get 3494 in before this?

**Review by shivadbhavsar — APPROVED** [review]
LGTM, but wait to merge till other PR is merged first and verify perf drop fix

**Pull request merged**
