### PR TITLE
Comment out qlinear reuse matcher

### PR DESCRIPTION
**Pull request by CharlieL7**
Comment out the qlinear_reused matcher because of an accuracy error for quantized resnet50

### CODE REVIEW

**Review by umangyadav — APPROVED** [review]

**Review by shivadbhavsar — APPROVED** [review]

**Comment by umangyadav** [comment]
Is this required if we were to pull in changes from MLIR ?

**Comment by CharlieL7** [comment]
> Is this required if we were to pull in changes from MLIR ?

We won't hit the verify "accuracy" bug for the quantized resnet50 model with the change from MLIR. However, the matcher itself is questionable. I'm proposing to remove it permanently here in #3269.

**Comment by pfultz2** [comment]
> We won't hit the verify "accuracy" bug for the quantized resnet50 model with the change from MLIR.

If we dont hit an accuracy error then we shouldn't remove it.

**Comment by CharlieL7** [comment]
> > We won't hit the verify "accuracy" bug for the quantized resnet50 model with the change from MLIR.
> 
> If we dont hit an accuracy error then we shouldn't remove it.

Matcher is brittle, if we change the randomized values slightly it will even fail without MLIR.

**Comment by CharlieL7** [comment]
Closing: Should be able to pass verify accuracy with this compiler pass enable with the MLIR fix https://github.com/ROCm/rocMLIR/pull/1567

**Pull request closed without merging**
