### PR TITLE
Onnx parsers for Quantization & Dequantization: case when scales and zero point tensors of same dimension as the input tensor

### PR DESCRIPTION
**Pull request by lakhinderwalia**
Onnx parsers for Quantization Dequantization: case when scales and zero point tensors of same dimension as the input tensor:
Currently these parsers try to either broadcast or multibroadcast. Also these two operators already handle scales in some inconsistent manner.

### CODE REVIEW

**Comment by pfultz2** [comment]
> case when scales and zero point tensors of same dimension as the input tensor:

I dont think the scales and zero points are ever the same shape as the input:

- Per-tensor: The scales and zero points are scalars, so we insert a simple broadcast
- Per-axis quantization: The scales and zero points are a 1-D tensor that will be broadcasts across the `axis`(which is defined as an attribute in the ONNX operator,  see [here](https://onnx.ai/onnx/operators/onnx__QuantizeLinear.html#attributes)). Since its 1-D we need to know the axis(we cant use a multibroadcast here).
- Blocked quantization: The scales and zero points have the same rank but different dimensions than the input. The `axis` of the dimension that is different than the input should be set to the `block_size`(which both `axis` and `block_size` are attributes define in the ONNX operator, see [here](https://onnx.ai/onnx/operators/onnx__QuantizeLinear.html#attributes)). 

So I dont see how they could ever be the same shape.

**Comment by lakhinderwalia** [comment]
> * Blocked quantization: The scales and zero points have the same rank but different dimensions than the input. The `axis` of the dimension that is different than the input should be set to the `block_size`(which both `axis` and `block_size` are attributes define in the ONNX operator, see [here](https://onnx.ai/onnx/operators/onnx__QuantizeLinear.html#attributes)).

@pfultz2, I am trying to work with an int4 model without implementing blocked quantization. And assume `block_size = 1`. And thus in simple case here, the scale tensor is the same shape as the input weights.

**Review by CharlieL7 — CHANGES_REQUESTED** [review]
Code changes look fine, should have ONNX parse tests to verify what it does.

**Comment by lakhinderwalia** [comment]
> Code changes look fine, should have ONNX parse tests to verify what it does.

There are tests being added to another PR, along with int4 type tensors in it. If you like I can add one separately, just let me know, thanks. 

(BTW, this case is just a degenerate case of where no broadcast or multicast is required for scales or zero_points.)

**Comment by pfultz2** [comment]
> > * Blocked quantization: The scales and zero points have the same rank but different dimensions than the input. The `axis` of the dimension that is different than the input should be set to the `block_size`(which both `axis` and `block_size` are attributes define in the ONNX operator, see [here](https://onnx.ai/onnx/operators/onnx__QuantizeLinear.html#attributes)).
> 
> @pfultz2, I am trying to work with an int4 model while blocked quantization is not implemented. And assume `block_size = 1`. And thus in simple case here, the scale tensor is the same shape as the input weights.

#3412 already handles block quantization for any block_size.

**Comment by lakhinderwalia** [comment]
> #3412 already handles block quantization for any block_size.

'Already'? As in back to the future? :-)

**Comment by CharlieL7** [comment]
> > Code changes look fine, should have ONNX parse tests to verify what it does.
> 
> There are tests being added to another PR, along with int4 type tensors in it. If you like I can add one separately, just let me know, thanks.
> 
> (BTW, this case is just a degenerate case of where no broadcast or multicast is required for scales or zero_points.)

Would be better to have a test for this degenerate case, but not essentially right now. Approving

**Review by CharlieL7 — APPROVED** [review]

**Review by pfultz2 — CHANGES_REQUESTED** [review]
I dont think this should be merged in. #3412 already handles this case, and if we merge this PR in, its just going to cause merge conflicts for #3412. I dont think this make sense to have all the extra churn for a "degenerate" case which is not used for any models.

**Comment by lakhinderwalia** [comment]
> Would be better to have a test for this degenerate case, but not essentially right now. Approving

Thanks for approving, Charlie. The test graph for the degenerate case has actually already been added in a different PR.

**Comment by lakhinderwalia** [comment]
> I dont think this should be merged in. #3412 already handles this case, and if we merge this PR in, its just going to cause merge conflicts for #3412. I dont think this make sense to have all the extra churn for a "degenerate" case which is not used for any models.

Thanks, @pfultz2, yes at this point we don't want the churn. I would have appreciated your early approval. This work was done 3 weeks ago, and now wasted.

**Comment by lakhinderwalia** [comment]
Closing this one. This work has been subsequently done in [3412](https://github.com/ROCm/AMDMIGraphX/pull/3412).

**Pull request closed without merging**
