### PR TITLE
Add layout attribute support for GRU operator

### PR DESCRIPTION
**Pull request by nives-vukovic**
Since ONNX opset version 14, layout attribute has been introduced to GRU operator which allows two predefined layouts for input and output shapes.

Add corresponding reference, onnx, and verify tests.

Resolves https://github.com/migraphx-benchmark/AMDMIGraphX/issues/133

### CODE REVIEW

**Review by CharlieL7 — APPROVED** [review]

**Review by TedThemistokleous — APPROVED** [review]

**Review by TedThemistokleous — COMMENTED** [review]
Fix CI but otherwise looks good

**Comment by TedThemistokleous** [comment]
Seeing some odd behavior with CI

```
[2023-12-19T19:46:43.107Z] make[2]: *** Waiting for unfinished jobs....

[2023-12-19T19:46:43.107Z] ccache: error: Failed to create directory /var/jenkins/.cache/ccache/tmp: Permission denied

[2023-12-19T19:46:43.107Z] ccache: error: Failed to create directory /var/jenkins/.cache/ccache/tmp: Permission denied

[2023-12-19T19:46:43.107Z] ccache: error: Failed to create directory /var/jenkins/.cache/ccache/tmp: Permission denied

[2023-12-19T19:46:43.107Z] ccache: error: Failed to create directory /var/jenkins/.cache/ccache/tmp: Permission denied

[2023-12-19T19:46:43.107Z] ccache: error: Failed to create directory /var/jenkins/.cache/ccache/tmp: Permission denied

[2023-12-19T19:46:43.107Z] ccache: error: Failed to create directory /var/jenkins/.cache/ccache/tmp: Permission denied
```

**Review by lakhinderwalia — CHANGES_REQUESTED** [review]
Does this follow the spec, please?  https://onnx.ai/onnx/operators/onnx__GRU.html which says the default f = sigmoid, g = tanh. We don't seem to do that in gru_actv_functions().
Thanks.

**Comment by nives-vukovic** [comment]
@TedThemistokleous  The issue with performance tests exist due to the fact that this branch is from our repo, as at that time we did not have access rights for the main one. I believe Chris resolves it locally when all is approved and all comments are addressed.

**Comment by nives-vukovic** [comment]
@lakhinderwalia Although I didn't touch upon this part of code as the spec has not been changed recently (only the layout attribute has been added), I believe it is stated that std::vector<std::string> vec_names = {"sigmoid", "tanh"}; are default values, and they are correctly filled in if no activation functions are provided by the user. If some part of the parsed activation functions is not as expected, there is a readjustment function in src/rewrite_rnn.cpp (rewrite_rnn::gru_actv_funcs).

**Comment by lakhinderwalia** [comment]
> @lakhinderwalia Although I didn't touch upon this part of code as the spec has not been changed recently (only the layout attribute has been added), I believe it is stated that std::vectorstd::string vec_names = {"sigmoid", "tanh"}; are default values, and they are correctly filled in if no activation functions are provided by the user. If some part of the parsed activation functions is not as expected, there is a readjustment function in src/rewrite_rnn.cpp (rewrite_rnn::gru_actv_funcs).

@nives-vukovic, thanks. I know you didn't touch this code at all :-) 

However, the spec https://onnx.ai/onnx/operators/onnx__GRU.html says: 
_activations - STRINGS : A list of 2 (or 4 if bidirectional) activation functions for update, reset, and hidden gates. The activation functions must be one of the activation functions specified above. Optional: See the equations for default if not specified._

I wasn't pointing at your changes, but I think this gru_actv_funcs() is handling the spec. incorrectly for non-default case of activations, and this is a good time to clean it. We shouldn't be handling activation function list of size 1 or 3: Only 2 and 4, as specified. (Basically, flag errors for size 1 or 3, and also if they are not one of these three valid activation types: relu, tanh or sigmoid. I don't even know if we support the optional types.). That was my suggested change, just to clean it up, if it makes sense. Thanks.

**Comment by nives-vukovic** [comment]
@lakhinderwalia I agree that the current implementation does not seem to be completely in line with the specification, I have modified the parsing accordingly, and modified all migraphx calls to the gru operator so that they always contain either 2 or 4 activation functions. I have also modified onnx test files that had invalid number of activation functions (and that we have been able to support previously). The only thing that is left is a function that adds missing activation functions (if needed) inside the rewrite_rnn file. It is not directly connected to onnx, so I was not sure if it is the best idea to change it now.

It is important to mention that this same inconsistency regarding number of activation function exists also with lstm and rnn operator. They have already been merged, so if what is done here seems as a good solution, I can create a PR to clean those two as well.

**Review by lakhinderwalia — APPROVED** [review]
Thank you for removing the prior inconsistency, that wasn't related to your changes.

**Comment by causten** [comment]
Once the Format failure is fixed, then this will merge

**Comment by causten** [comment]
http://micimaster.amd.com/blue/organizations/jenkins/AMDMIGraphX/detail/PR-2415/3/pipeline/181
There's a failure

**Comment by nives-vukovic** [comment]
@causten I am not able to access the link.

**Pull request merged**
