### PR TITLE
matmulnbits zero_point fix

### PR DESCRIPTION
**Pull request by lakhinderwalia**
Currently the matmulnbits parsing introduces a fixed type `uint8_type` for zero_point, and misses `int8_type`.

### CODE REVIEW

**Review by kahmed10 — APPROVED** [review]

**Comment by kahmed10** [comment]
https://github.com/microsoft/onnxruntime/blob/main/docs/ContribOperators.md#com.microsoft.MatMulNBits according to the spec zero point can only be uint8/int32/float16/float?

**Comment by TedThemistokleous** [comment]
> > https://github.com/microsoft/onnxruntime/blob/main/docs/ContribOperators.md#com.microsoft.MatMulNBits according to the spec zero point can only be uint8/int32/float16/float?
> 
> And if the zero point isn't specified, it can be inferred to be `uint8` or `int32`, would be my guess. I should fix my test case, and do it for `int32` instead of `int8`.
> 
> @kahmed10, btw, I don't see any type checking in this parser code -- unless it is done somewhere else.

I don't think we can assume it is handled. If things are type constrained you'll need to add that for those inputs

**Review by causten — CHANGES_REQUESTED** [review]
Is this still needed?  Too many failures to approve

**Comment by lakhinderwalia** [comment]
> Is this still needed? Too many failures to approve

These failures have likely nothing to do with this change, @causten, because I added a fix for an `int8` type, which isn't exercised anywhere in the codebase. But this PR is still important to debug our current fusion issues, as I am debugging one right now. It is kept as a back-burner item. Thanks.

**Comment by lakhinderwalia** [comment]
Closing this. This test-model was used to verify a simple int8 test-case; The type checking can be added later, because `int8` case should have been flagged by the parser.

**Pull request closed without merging**
